/**
 * @name Demo Source
 * @version 1.2
 * @lang en
 *
 * Invented series with generated artwork, for store screenshots and demos. Nothing here is
 * scraped: the catalog is embedded below and images are served from this repo.
 *
 * GENERATED by tools/generate.py from catalog.json. Edit the template, not main.js.
 */

const REPO_URL = 'https://github.com/codertheory/mangasteen-demo-source';
const ASSETS = 'https://raw.githubusercontent.com/codertheory/mangasteen-demo-source/main/assets';
const PAGE_SIZE = 12;
const PAGE_COUNT = 12;
const HOUR = 3600 * 1000;
const WEEK = 7 * 24 * HOUR;

const CATALOG = [
    {
        "slug": "lanterns-over-kiriyama",
        "title": "Lanterns over Kiriyama",
        "author": "Aoi Mitsuda",
        "genres": [
            "Fantasy",
            "Adventure",
            "Drama"
        ],
        "status": "Ongoing",
        "chapters": 64,
        "hoursAgo": 2,
        "description": "A night-market lantern maker discovers that the lights she sells guide lost spirits home, and that someone is buying them all."
    },
    {
        "slug": "the-quiet-orbit",
        "title": "The Quiet Orbit",
        "author": "Ren Halloway",
        "genres": [
            "Sci-Fi",
            "Drama",
            "Mystery"
        ],
        "status": "Ongoing",
        "chapters": 41,
        "hoursAgo": 5,
        "description": "The last engineer on a drifting research station keeps receiving messages from a crew that left forty years ago."
    },
    {
        "slug": "bento-for-two",
        "title": "Bento for Two",
        "author": "Mika Sonoda",
        "genres": [
            "Slice of Life",
            "Romance",
            "Comedy"
        ],
        "status": "Ongoing",
        "chapters": 88,
        "hoursAgo": 9,
        "description": "Two rival cooking-club members agree to trade lunches every day until one of them admits the other is better."
    },
    {
        "slug": "iron-tea-house",
        "title": "Iron Tea House",
        "author": "Kenji Arawa",
        "genres": [
            "Action",
            "Martial Arts",
            "Comedy"
        ],
        "status": "Ongoing",
        "chapters": 112,
        "hoursAgo": 14,
        "description": "A retired fighter opens a tea house on the busiest street in the capital. Every customer wants a rematch."
    },
    {
        "slug": "paper-cranes-at-dawn",
        "title": "Paper Cranes at Dawn",
        "author": "Yuna Kaede",
        "genres": [
            "Drama",
            "Slice of Life"
        ],
        "status": "Completed",
        "chapters": 36,
        "hoursAgo": 20,
        "description": "A high-school senior folds one crane every morning for a friend in hospital, and starts leaving notes inside them."
    },
    {
        "slug": "static-and-snow",
        "title": "Static & Snow",
        "author": "Oren Vale",
        "genres": [
            "Mystery",
            "Thriller"
        ],
        "status": "Ongoing",
        "chapters": 27,
        "hoursAgo": 26,
        "description": "A mountain town's only radio station starts broadcasting tomorrow's weather, and tomorrow's news."
    },
    {
        "slug": "the-cartographers-apprentice",
        "title": "The Cartographer's Apprentice",
        "author": "Lio Brandt",
        "genres": [
            "Adventure",
            "Fantasy"
        ],
        "status": "Ongoing",
        "chapters": 53,
        "hoursAgo": 31,
        "description": "Maps drawn by her master change the land they describe. His apprentice has just found his last, unfinished one."
    },
    {
        "slug": "neon-koi",
        "title": "Neon Koi",
        "author": "Sora Ibuki",
        "genres": [
            "Action",
            "Sci-Fi"
        ],
        "status": "Ongoing",
        "chapters": 75,
        "hoursAgo": 40,
        "description": "In a flooded megacity, a courier on a stolen hover-bike delivers the one package nobody else will touch."
    },
    {
        "slug": "second-hand-spells",
        "title": "Second-Hand Spells",
        "author": "Hana Moriyama",
        "genres": [
            "Fantasy",
            "Comedy",
            "Slice of Life"
        ],
        "status": "Ongoing",
        "chapters": 49,
        "hoursAgo": 47,
        "description": "A thrift shop for used magic items, run by a clerk who can't cast a single spell herself."
    },
    {
        "slug": "the-long-relay",
        "title": "The Long Relay",
        "author": "Taro Ishide",
        "genres": [
            "Sports",
            "Drama"
        ],
        "status": "Ongoing",
        "chapters": 96,
        "hoursAgo": 55,
        "description": "A washed-up university track team has one year to qualify for the hundred-kilometre New Year relay."
    },
    {
        "slug": "moth-and-meridian",
        "title": "Moth & Meridian",
        "author": "Elise Marrow",
        "genres": [
            "Romance",
            "Fantasy"
        ],
        "status": "Completed",
        "chapters": 60,
        "hoursAgo": 70,
        "description": "A night-shift clockmaker and a lighthouse keeper exchange letters by moth for a whole winter."
    },
    {
        "slug": "garden-of-small-robots",
        "title": "Garden of Small Robots",
        "author": "Pim Okada",
        "genres": [
            "Sci-Fi",
            "Slice of Life"
        ],
        "status": "Ongoing",
        "chapters": 22,
        "hoursAgo": 80,
        "description": "An old botanist builds a dozen tiny robots to tend her garden after she moves away. They have opinions."
    },
    {
        "slug": "salt-road",
        "title": "Salt Road",
        "author": "Idris Kolt",
        "genres": [
            "Historical",
            "Adventure",
            "Drama"
        ],
        "status": "Ongoing",
        "chapters": 38,
        "hoursAgo": 96,
        "description": "Caravan guards, a runaway scholar and a camel with a grudge cross a desert that keeps rearranging itself."
    },
    {
        "slug": "after-the-bell",
        "title": "After the Bell",
        "author": "Nami Tachibana",
        "genres": [
            "School Life",
            "Comedy",
            "Romance"
        ],
        "status": "Ongoing",
        "chapters": 104,
        "hoursAgo": 120,
        "description": "The school's three most unlucky students form a club to help everyone else's luck, with mixed results."
    },
    {
        "slug": "hollow-crown-academy",
        "title": "Hollow Crown Academy",
        "author": "Viktor Ashe",
        "genres": [
            "Fantasy",
            "Action",
            "School Life"
        ],
        "status": "Ongoing",
        "chapters": 131,
        "hoursAgo": 150,
        "description": "A commoner enrols in a royal academy by accident, and the entrance exam turns out to be a real war."
    },
    {
        "slug": "tidewater-diner",
        "title": "Tidewater Diner",
        "author": "June Calloway",
        "genres": [
            "Slice of Life",
            "Drama"
        ],
        "status": "Completed",
        "chapters": 18,
        "hoursAgo": 190,
        "description": "Regulars at a seaside diner tell the new waitress the stories behind the photos on the wall."
    },
    {
        "slug": "wolfsbane-express",
        "title": "Wolfsbane Express",
        "author": "Greta Holm",
        "genres": [
            "Mystery",
            "Supernatural"
        ],
        "status": "Ongoing",
        "chapters": 45,
        "hoursAgo": 230,
        "description": "A night train that only runs on full moons, and a conductor who never checks tickets."
    },
    {
        "slug": "the-ninth-kitchen",
        "title": "The Ninth Kitchen",
        "author": "Daichi Fuse",
        "genres": [
            "Comedy",
            "Slice of Life"
        ],
        "status": "Ongoing",
        "chapters": 70,
        "hoursAgo": 280,
        "description": "Eight restaurants failed in this building. The ninth is run by someone who can't cook, and it's full every night."
    },
    {
        "slug": "starlit-archive",
        "title": "Starlit Archive",
        "author": "Celeste Ono",
        "genres": [
            "Fantasy",
            "Mystery"
        ],
        "status": "Ongoing",
        "chapters": 33,
        "hoursAgo": 330,
        "description": "Every book in the observatory library records a star. Someone has started tearing out pages."
    },
    {
        "slug": "copper-and-clay",
        "title": "Copper & Clay",
        "author": "Ansel Reed",
        "genres": [
            "Drama",
            "Historical"
        ],
        "status": "Completed",
        "chapters": 42,
        "hoursAgo": 400,
        "description": "Two potters in a river town compete for the same royal commission across one very long summer."
    },
    {
        "slug": "the-last-arcade",
        "title": "The Last Arcade",
        "author": "Kai Morrow",
        "genres": [
            "Comedy",
            "Sci-Fi"
        ],
        "status": "Ongoing",
        "chapters": 29,
        "hoursAgo": 460,
        "description": "The final arcade in a city of VR headsets, kept alive by a clerk, a champion and one haunted cabinet."
    },
    {
        "slug": "foxfire-post-office",
        "title": "Foxfire Post Office",
        "author": "Rin Asahi",
        "genres": [
            "Supernatural",
            "Slice of Life"
        ],
        "status": "Ongoing",
        "chapters": 57,
        "hoursAgo": 520,
        "description": "A country post office that also delivers mail for foxes, tanuki and the occasional mountain god."
    },
    {
        "slug": "glass-harbor",
        "title": "Glass Harbor",
        "author": "Mara Lind",
        "genres": [
            "Romance",
            "Drama"
        ],
        "status": "Ongoing",
        "chapters": 24,
        "hoursAgo": 600,
        "description": "A glassblower returns to the harbour town she left, and to the ferry captain who never did."
    },
    {
        "slug": "thunder-in-the-rice-fields",
        "title": "Thunder in the Rice Fields",
        "author": "Goro Nakabe",
        "genres": [
            "Action",
            "Comedy",
            "Supernatural"
        ],
        "status": "Ongoing",
        "chapters": 83,
        "hoursAgo": 700,
        "description": "A thunder spirit crash-lands in a farming village and is put to work until the harvest is in."
    }
];

// Dates are relative to "now" so Latest and the chapter lists always look recently updated.
// Emitted as numeric strings: older app builds mis-decode large JS numbers.
function msString(ms) {
    return Math.max(0, ms).toFixed(0);
}

function latestChapterAt(entry) {
    return Date.now() - entry.hoursAgo * HOUR;
}

function toManga(entry) {
    return {
        title: entry.title,
        url: REPO_URL + '#' + entry.slug,
        coverUrl: ASSETS + '/covers/' + entry.slug + '.jpg',
        description: entry.description,
        author: entry.author,
        artist: entry.author,
        status: entry.status,
        genres: entry.genres.slice(),
        lastUpdate: msString(latestChapterAt(entry)),
    };
}

function chaptersOf(entry) {
    const newest = latestChapterAt(entry);
    const chapters = [];
    for (let n = entry.chapters; n >= 1; n--) {
        chapters.push({
            name: 'Chapter ' + n,
            url: REPO_URL + '#' + entry.slug + '/' + n,
            number: n,
            uploadDate: msString(newest - (entry.chapters - n) * WEEK),
        });
    }
    return chapters;
}

function entryFor(url) {
    const slug = String(url || '').split('#')[1] || '';
    return CATALOG.find(e => e.slug === slug.split('/')[0]) || null;
}

function paged(list, page) {
    const p = page > 1 ? page : 1;
    return list.slice((p - 1) * PAGE_SIZE, p * PAGE_SIZE);
}

// The demo catalog has no adult titles, so `options.hideAdult` needs no handling.
async function getPopularManga(page) {
    // Catalog order is the popularity order.
    return paged(CATALOG, page).map(toManga);
}

async function getLatestManga(page) {
    const byLatest = CATALOG.slice().sort((a, b) => a.hoursAgo - b.hoursAgo);
    return paged(byLatest, page).map(toManga);
}

async function searchManga(query, page) {
    const q = String(query || '').trim().toLowerCase();
    if (!q) return [];
    const hits = CATALOG.filter(e =>
        e.title.toLowerCase().includes(q) ||
        e.author.toLowerCase().includes(q) ||
        e.genres.some(g => g.toLowerCase() === q));
    return paged(hits, page).map(toManga);
}

async function getMangaDetails(url) {
    const entry = entryFor(url);
    if (!entry) return null;
    return { manga: toManga(entry), chapters: chaptersOf(entry) };
}

async function getChapterList(url) {
    const entry = entryFor(url);
    return entry ? chaptersOf(entry) : [];
}

async function getPageList(url) {
    // Every chapter cycles through the shared pages, starting at a different one.
    const n = parseInt(String(url).split('/').pop(), 10) || 1;
    const pages = [];
    for (let i = 0; i < PAGE_COUNT; i++) {
        const k = ((n + i) % PAGE_COUNT) + 1;
        pages.push(ASSETS + '/pages/p' + String(k).padStart(2, '0') + '.jpg');
    }
    return pages;
}
